name: Build & Release

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.8"

      - name: Grant execute permission to gradlew
        run: chmod +x gradlew

      - name: Get version from build.gradle
        id: get_version
        run: |
          VERSION=$(./gradlew -q printVersion)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build with Gradle
        run: gradle build

      - name: Archive Plugin Jar
        run: |
          mkdir -p release
          cp build/libs/*.jar release/PlayerHome.jar
          ls -la release

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.VERSION }}
          release_name: "PlayerHome v${{ env.VERSION }}"
          files: release/PlayerHome.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
